vich_uploader:
    db_driver: orm

    mappings:
        cryptocurrencies_logo:
            uri_prefix: '%cryptocurrencies_logo%'
            upload_destination: '%kernel.project_dir%/public%cryptocurrencies_logo%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true 
            delete_on_update: false
